### ISSUE TITLE
Erro ao abrir o Portugol-Studio no osX Monterey

### ISSUE THREAD

**Issue by AnTonhoLAB** [UNIVALI-LITE/Portugol-Studio#1034] opened 2022-03-21 22:48 UTC
Portugol-Studio não abre no osX Monterey 

Process:               java [1870]
Path:                  /Applications/Portugol Studio.app/Contents/Resources/IDE/java/java-mac/bin/java
Identifier:            java
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        Exited process [1850]
User ID:               501

Date/Time:             2022-03-21 19:34:30.9802 -0300
OS Version:            macOS 12.2.1 (21D62)
Report Version:        12
Anonymous UUID:        8CACFEBE-CBE0-DC21-41AE-D3E7056E032D

Sleep/Wake UUID:       D5B1B0CB-6389-4721-8B00-BE152DC9CB9B

Time Awake Since Boot: 7300 seconds
Time Since Wake:       3493 seconds

System Integrity Protection: disabled

Crashed Thread:        0  AppKit Thread  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00007f90b0528000
Exception Codes:       0x0000000000000001, 0x00007f90b0528000
Exception Note:        EXC_CORPSE_NOTIFY

VM Region Info: 0x7f90b0528000 is not in any region.  Bytes after previous region: 1  Bytes before following region: 1024000
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      MALLOC_LARGE             7f90b04f7000-7f90b0528000 [  196K] rw-/rwx SM=PRV  
--->  GAP OF 0xfa000 BYTES
      MALLOC_LARGE             7f90b0622000-7f90b071c000 [ 1000K] rw-/rwx SM=PRV  

Application Specific Information:
abort() called

Thread 0 Crashed:: AppKit Thread Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff803e37112 __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff803e6d214 pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff803db9d10 abort + 123
3   libjvm.dylib                  	       0x108752ad9 os::abort(bool) + 25
4   libjvm.dylib                  	       0x10887ad22 VMError::report_and_die() + 2304
5   libjvm.dylib                  	       0x10875471e JVM_handle_bsd_signal + 1131
6   libjvm.dylib                  	       0x108750963 signalHandler(int, __siginfo*, void*) + 47
7   libsystem_platform.dylib      	    0x7ff803e82e2d _sigtramp + 29
8   ???                           	    0x7ff8454f7998 OBJC_CLASS_$_NSCalendar + 40
9   ???                           	               0x3 ???
10  Foundation                    	    0x7ff804d5e93e NSCopyMemoryPages + 57
11  Foundation                    	    0x7ff804d6703f -[NSConcreteMutableData appendBytes:length:] + 514
12  Foundation                    	    0x7ff804d7e487 -[NSData(NSData) enumerateByteRangesUsingBlock:] + 105
13  Foundation                    	    0x7ff804ddeed9 -[NSData(NSData) mutableCopyWithZone:] + 173
...

Model: MacBookPro12,1, BootROM 428.60.3.0.0, 2 processors, Dual-Core Intel Core i5, 2,7 GHz, 8 GB, SMC 2.28f7
Graphics: Intel Iris Graphics 6100, Intel Iris Graphics 6100, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1867 MHz, 0x02FE, 0x4544464132333241324D412D4A442D460000
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1867 MHz, 0x02FE, 0x4544464132333241324D412D4A442D460000
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x133), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1710.3)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0128G, 121,33 GB
USB Device: USB30Bus
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

**Comment by AdsonEsteves** [comment] 2022-03-24 03:18
Duplicate of #990

**Closed by AdsonEsteves** 2022-03-24 03:18 UTC
