### ISSUE TITLE
Erro numero 863adcd570b9c38e5e74b35656a1b466d5e0738b v2.7.2

### ISSUE THREAD

**Issue by gean444** [UNIVALI-LITE/Portugol-Studio#688] opened 2019-04-04 00:02 UTC
br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.NullPointerException
	at br.univali.ps.nucleo.TratadorExcecoes.uncaughtException(TratadorExcecoes.java:131)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.lang.Thread.dispatchUncaughtException(Thread.java:1959)
Caused by: java.lang.NullPointerException
	at br.univali.ps.nucleo.LogManager$1.run(LogManager.java:59)

**Comment by AdsonEsteves** [comment] 2019-04-05 19:40
Duplicate of #669

**Closed by AdsonEsteves** 2019-04-05 19:40 UTC
