### ISSUE TITLE
Erro na instalacao Mac Big Sur 11.0.1

### ISSUE THREAD

**Issue by FabioVeiga** [UNIVALI-LITE/Portugol-Studio#909] opened 2021-01-22 02:52 UTC
**Descrição do Problema**:
Instala corretamente, mas na hora de executar, apresenta um erro Unexpected
**Mensagem de Erro (se houver)**:
Process:               java [23346]
Path:                  /Applications/Portugol Studio.app/Contents/Resources/IDE/java/java-mac/bin/java
Identifier:            net.java.openjdk.cmd
Version:               1.0 (1.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [23326]
Responsible:           java [23346]
User ID:               501

Date/Time:             2021-01-21 23:48:19.399 -0300
OS Version:            macOS 11.0.1 (20B29)
Report Version:        12
Bridge OS Version:     5.0.1 (18P2561)
Anonymous UUID:        AA66E132-B5AA-7B7A-7297-AC443FD0567C

Sleep/Wake UUID:       E0DEC980-A236-41D9-9633-A38AB8B2EE44

Time Awake Since Boot: 94000 seconds
Time Since Wake:       7100 seconds

System Integrity Protection: enabled

Crashed Thread:        0  AppKit Thread  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00007fc0b1e84000
Exception Note:        EXC_CORPSE_NOTIFY

**Captura de Tela / Arquivo.por**:
<img width="1009" alt="Screen Shot 2021-01-21 at 11 48 42 PM" src="https://user-images.githubusercontent.com/52764579/105439369-804c9980-5c43-11eb-97d2-dc33599097d7.png">

**Especificações do sistema**:
<img width="533" alt="Screen Shot 2021-01-21 at 11 51 33 PM" src="https://user-images.githubusercontent.com/52764579/105439432-9d816800-5c43-11eb-93ce-1dd6661de230.png">

**Comment by AdsonEsteves** [comment] 2021-01-28 06:02
Obrigado pelo reporte, ainda não sabemos qual o problema, mas vamos resolver assim que possível

**Comment by AdsonEsteves** [comment] 2021-01-28 06:02
Duplicate of #880

**Closed by AdsonEsteves** 2021-01-28 06:02 UTC
