### ISSUE TITLE
Erro numero xxx

### ISSUE THREAD

**Issue by Davi1504** [UNIVALI-LITE/Portugol-Studio#482] opened 2018-02-12 11:41 UTC
> Esta issue foi gerada automaticamente

[br.univali.ps.nucleo.ExcecaoAplicacao: java.lang.IllegalArgumentException: bad position: 136
	at br.univali.ps.nucleo.TratadorExcecoes.transformarExcecao(TratadorExcecoes.java:220)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:41)
	at br.univali.ps.ui.telas.TelaPrincipal.lambda$abrirArquivosCodigoFonte$1(TelaPrincipal.java:273)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecaoDetalhada(TratadorExcecoes.java:105)
	at br.univali.ps.nucleo.TratadorExcecoes.exibir(TratadorExcecoes.java:78)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:48)
	at br.univali.ps.ui.telas.TelaPrincipal.lambda$abrirArquivosCodigoFonte$1(TelaPrincipal.java:273)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalArgumentException: bad position: 136
	at javax.swing.text.JTextComponent.setCaretPosition(JTextComponent.java:1629)
	at br.univali.ps.ui.editor.Editor.carregarPosicaoCursor(Editor.java:1035)
	at br.univali.ps.ui.editor.Editor.carregarInformacoesPortugolStudio(Editor.java:995)
	at br.univali.ps.ui.editor.Editor.setCodigoFonte(Editor.java:988)
	at br.univali.ps.ui.abas.AbaCodigoFonte.setCodigoFonte(AbaCodigoFonte.java:1322)
	at br.univali.ps.ui.telas.TelaPrincipal.lambda$abrirArquivosCodigoFonte$1(TelaPrincipal.java:266)
	... 39 more
]

**Comment by AdsonEsteves** [comment] 2018-02-14 04:51
Duplicate of #454

**Comment by AdsonEsteves** [comment] 2018-02-14 04:52
@Davi1504 

Esse problema já foi relatado e na próxima versão estará disponível resolvido.

**Closed by AdsonEsteves** 2018-02-14 04:52 UTC
