### ISSUE TITLE
Operation not permitted 232eb157562ea11adefaa7bce70322a5ef14bd79 v2.7.4

### ISSUE THREAD

**Issue by jmapsimoes** [UNIVALI-LITE/Portugol-Studio#733] opened 2019-11-09 10:06 UTC
> Esta issue foi gerada automaticamente

Erro surgiu após instalar MacOS Catalina 10.15.1

<img width="502" alt="Captura de ecrã 2019-11-09, às 10 04 34" src="https://user-images.githubusercontent.com/9195015/68526887-92f5df80-02d8-11ea-9e78-62ec39c15cf1.png">

[pressione o botao "copiar erro" no Portugol Studio e cole o erro aqui antes de enviar]
br.univali.ps.nucleo.ExcecaoAplicacao: java.io.FileNotFoundException: /Users/jmapsimoes/Documents/ISPGaya/Portugol/parOuImpar.por (Operation not permitted)
	at br.univali.ps.nucleo.TratadorExcecoes.transformarExcecao(TratadorExcecoes.java:267)
	at br.univali.ps.nucleo.TratadorExcecoes.exibirExcecao(TratadorExcecoes.java:42)
	at br.univali.ps.ui.paineis.PainelExemplos.atualizarRecentes(PainelExemplos.java:444)
	at br.univali.ps.ui.paineis.PainelExemplos.<init>(PainelExemplos.java:159)
	at br.univali.ps.ui.abas.AbaInicial.initComponents(AbaInicial.java:365)
	at br.univali.ps.ui.abas.AbaInicial.<init>(AbaInicial.java:44)
	at br.univali.ps.ui.telas.TelaPrincipal.criaAbas(TelaPrincipal.java:122)
	at br.univali.ps.ui.telas.TelaPrincipal.<init>(TelaPrincipal.java:65)
	at br.univali.ps.ui.window.OutsidePanel.initComponents(OutsidePanel.java:64)
	at br.univali.ps.ui.window.OutsidePanel.<init>(OutsidePanel.java:25)
	at br.univali.ps.nucleo.PortugolStudio$2.run(PortugolStudio.java:780)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.FileNotFoundException: /Users/jmapsimoes/Documents/ISPGaya/Portugol/parOuImpar.por (Operation not permitted)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at br.univali.ps.ui.utils.FileHandle.read(FileHandle.java:61)
	at br.univali.ps.ui.utils.FileHandle.open(FileHandle.java:56)
	at br.univali.ps.ui.paineis.PainelExemplos.atualizarRecentes(PainelExemplos.java:405)
	... 22 more

**Comment by AdsonEsteves** [comment] 2020-04-29 01:52
Duplicate of #784

**Closed by AdsonEsteves** 2020-04-29 01:52 UTC
